import pymongo
import json

# Initialize connection to MongoDB (replace with your actual connection string)
def init_mongo_connection():
    client = pymongo.MongoClient("mongodb://localhost:27017")  # Replace with your MongoDB URI if needed
    return client

# Insert posts into MongoDB collection
def insert_posts_to_mongo(posts):
    client = init_mongo_connection()
    db = client['linkedin_posts_db']   # Database name (replace if needed)
    collection = db['posts']           # Collection name

    result = collection.insert_many(posts)
    print(f"Inserted {len(result.inserted_ids)} posts into MongoDB.")

if __name__ == "__main__":
    # Load the generated posts from JSON file (generated by generate_data.py)
    with open("fake_posts.json", 'r') as f:
        fake_posts = json.load(f)

    # Insert the posts into MongoDB
    insert_posts_to_mongo(fake_posts)